# Generated by Django 4.1 on 2022-08-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_alter_photo_cartegory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo", old_name="cartegory", new_name="category",
        ),
    ]
